### ISSUE TITLE
Permiso repo friender

### ISSUE THREAD

**Issue by caindestal** [Oxisrock/friender#1]
Hola,

Ya me baje el código y modifique las rutas de los modelos user y company, ademas creé el modelo services como me sugeriste. Quiero subirlo para que lo veas, solo faltaria las vistas, algo de validaciones y documentación de los modelos oferts/services
pero quiero hacer una rama (estaba por llamarla Modulo_ofertas) y no tengo permiso en tu repo, creo que debemos ir trabajando en un solo repo para no enredarnos. ¿o mejor continuo y modifico el que subi yo? 

Me avisas que opinas del nombre y como vamos a trabajar en los repos.

Salu2

**Comment by Oxisrock** [comment]
ok no hay lio
